# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162Ss2p7B0JKHIHJhHO95iDRmnlHLyMFt
"""

import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import joblib

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("pig_biosecurity_dataset_v1.csv")

X = df[[
    "Farm_Size_Acres_Norm",
    "Total_Pigs_Norm",
    "Nearby_Farm_50m",
    "Proper_Fencing",
    "Clean_Dirty_Zones",
    "Avg_Visitors_Day_Norm",
    "Introduce_Without_Quarantine",
    "Separate_Spaces",
    "Batch_Age_Weeks_Norm",
    "Previously_Infected",
    "Vacc_Coverage_Rate",
    "Pig_Density_Norm"
]]

y = df["Biosecurity_Risk_Label"]   # 0=Low, 1=Medium, 2=High

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Train LightGBM model
model = lgb.LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)
model.fit(X_train, y_train)

# 5. Evaluate
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred, target_names=["Low", "Medium", "High"]))

# 6. Save trained model
joblib.dump(model, "pig_risk_model.pkl")
print("✅ Model saved as risk_model.pkl")

